// CHECKSTYLE:OFF
/**
 * Source code generated by Fluent Builders Generator
 * Do not modify this file
 * See generator home page at: http://code.google.com/p/fluent-builders-generator-eclipse-plugin/
 */

package demo.pojo;

import java.util.Date;

public class PersonneBuilder extends PersonneBuilderBase<PersonneBuilder> {
	public static PersonneBuilder personne() {
		return new PersonneBuilder();
	}

	public PersonneBuilder() {
		super(new Personne());
	}

	public Personne build() {
		return getInstance();
	}
}

class PersonneBuilderBase<GeneratorT extends PersonneBuilderBase<GeneratorT>> {
	private Personne instance;

	protected PersonneBuilderBase(Personne aInstance) {
		instance = aInstance;
	}

	protected Personne getInstance() {
		return instance;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withNom(String aValue) {
		instance.setNom(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withPrenom(String aValue) {
		instance.setPrenom(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withAdresse(Adresse aValue) {
		instance.setAdresse(aValue);

		return (GeneratorT) this;
	}

	public AdresseAdresseBuilder withAdresse() {
		Adresse obj = new Adresse();

		withAdresse(obj);

		return new AdresseAdresseBuilder(obj);
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withDtNaissance(Date aValue) {
		instance.setDtNaissance(aValue);

		return (GeneratorT) this;
	}

	public class AdresseAdresseBuilder extends
			AdresseBuilderBase<AdresseAdresseBuilder> {
		public AdresseAdresseBuilder(Adresse aInstance) {
			super(aInstance);
		}

		@SuppressWarnings("unchecked")
		public GeneratorT endAdresse() {
			return (GeneratorT) PersonneBuilderBase.this;
		}
	}

	public static class AdresseBuilderBase<GeneratorT extends AdresseBuilderBase<GeneratorT>> {
		private Adresse instance;

		protected AdresseBuilderBase(Adresse aInstance) {
			instance = aInstance;
		}

		protected Adresse getInstance() {
			return instance;
		}

		@SuppressWarnings("unchecked")
		public GeneratorT withZipCode(String aValue) {
			instance.setZipCode(aValue);

			return (GeneratorT) this;
		}
	}
}
